name: Prod deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'LuisEnMarroquin/json-as-xlsx'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc
      - run: yarn
      - run: yarn test
      - run: yarn build
      - name: Copy files to library output folder
        run: |
          cp README.md packages/main-library/README.md
          cp LICENSE packages/main-library/LICENSE
      - name: Set environment variable for GitHub
        run: |
          echo "CURRENT_VERSION=$(node -e "console.log('v' + require('./package.json').version)")" >> $GITHUB_ENV
          echo CURRENT_VERSION ${{ env.CURRENT_VERSION }}
        working-directory: packages/main-library/
      - name: Publish package to NPM registry
        run: npm publish --provenance --access public
        working-directory: packages/main-library/
      - name: Create a new GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.CURRENT_VERSION }} -F README.md -t "Released ${{ env.CURRENT_VERSION }}"
      - name: Prepare static files for deployment
        run: yarn run static
      - uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: build
          branch: gh-pages
          git-config-name: LuisEnMarroquin
          git-config-email: mluis651@gmail.com
